feat: add new helix endpoints & fields, add eventsub-common module
twitch4j/twitch4j pull request #231
Opened 2020-12-06 09:31 UTC by iProdigy

### Prerequisites for Code Changes
* [x] This pull request follows the code style of the project
* [ ] I have tested this feature

### Changes Proposed
* Add game_name to Stream
* Add created_at to User
* Add custom reward/redemption endpoints
* Add eventsub helix endpoints
* Create eventsub-common module

### Additional Information
https://blog.twitch.tv/en/2020/11/13/twitch-developer-day-2020-introducing-the-channel-points-api-eventsub-and-more/
https://dev.twitch.tv/docs/change-log

2020-12-11 21:05 UTC, iProdigy commented on eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/UserUpdateEvent.java
> +@EqualsAndHashCode(callSuper = true)
```suggestion
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
```

2020-12-11 21:05 UTC, iProdigy commented on eventsub-common/src/main/java/com/github/twitch4j/eventsub/events/UserUpdateEvent.java
> +
```suggestion
import lombok.ToString;

```

2020-12-11 21:05 UTC, iProdigy commented on rest-helix/src/main/java/com/github/twitch4j/helix/eventsub/EventSubTransport.java
> +    private String secret;
Could provide a helper for verifying signatures via HMAC-SHA256

2020-12-23 17:19 UTC, iProdigy commented on eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubNotification.java
> +    private Object rawEvent;
Should we write a custom deserializer for this class instead of saving this Map and converting to an object later?

2020-12-29 22:52 UTC, Alex7892014 commented
Would be nice if this change released soon.
I need the new helix channel point api :)

2021-01-13 05:03 UTC, iProdigy commented on eventsub-common/src/main/java/com/github/twitch4j/eventsub/EventSubSubscription.java
> +    public EventSubSubscription(String id, EventSubSubscriptionStatus status, String type, String version, Map<String, Object> condition, Instant createdAt, EventSubTransport transport) {
If we annotate these args with `@JsonProperty`, `jackson-module-parameter-names` will no longer be used and we can remove the `-parameters` option on `javac` (see `build.gradle`). Let me know if this is desired

2021-01-17 00:13 UTC, PhilippHeuer requested changes
Looks very good, just one point and then we can merge this :)

2021-01-17 00:13 UTC, PhilippHeuer commented on common/src/main/java/com/github/twitch4j/common/util/TypeConvert.java
> +        .propertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE)
`PropertyNamingStrategy.SNAKE_CASE` is deprecated and replaced by `PropertyNamingStrategies.SNAKE_CASE`

2021-01-17 00:37 UTC, PhilippHeuer approved these changes

2021-01-17 01:26 UTC, merged