build: shadow jar - all deps in one jar
twitch4j/twitch4j pull request #244
Opened 2020-12-21 19:18 UTC by stachu540

### Prerequisites for Code Changes
* [x] This pull request follows the code style of the project
* [x] I have tested this feature

### Changes Proposed
1. Apply plugin `com.github.johnrengelman.shadow` - Closes #226 

### Additional Information 
In #226 where providing this plugin and applying `shaded` word into `archiveClassifier` for `shadowJar` task, will automatically adds into `MavenPublication`. 

All those changes are be tested before the pull request.

2020-12-22 12:31 UTC, PhilippHeuer requested changes
Should we relocate all packages to avoid conflicts with other dependencies and also with ourselves? (ie. to allow ppl to use the shaded TwitchChat 1.0 together with shaded TwitchPubSub 1.1 as single modules)

> https://imperceptiblethoughts.com/shadow/configuration/relocation/#automatically-relocating-dependencies

We would just need to use a unique prefix for each module.

2020-12-22 23:16 UTC, stachu540 commented on deployment.gradle
> +
```suggestion
task shadowJarRelocate(type: com.github.jengelman.gradle.plugins.shadow.tasks.ConfigureShadowRelocation) {
	target = shadowJar
	prefix - "t4j" // up to you
}

// Shadow Jar
shadowJar {
	dependsOn shadowJarRelocate
	archiveClassifier.set('shaded')
	manifest {
		inheritFrom jar.manifest
	}
}
```

2021-01-04 19:07 UTC, PhilippHeuer approved these changes
Had to change it a little because the example in the shadow documentation wasn't working, but it works now.

2021-01-04 19:11 UTC, merged

2021-01-04 19:44 UTC, stachu540 commented
#226 Closed