feat: add unofficial badge endpoints
twitch4j/twitch4j pull request #302
Opened 2021-03-20 19:49 UTC by iProdigy

### Prerequisites for Code Changes
* [x] This pull request follows the code style of the project
* [x] I have tested this feature

### Changes Proposed
* Add `TwitchKraken#getGlobalBadges(String)`
* Add `TwitchKraken#getChannelBadges(String, String)`

### Additional Information 
https://discuss.dev.twitch.tv/t/beta-badge-api/6388

2021-03-28 21:14 UTC, PhilippHeuer requested changes
I think the badges code might be a better fit for the tmi module as it's related to chat and isn't a kraken method. Maybe we could use tmi for any future api methods that are not kraken or helix.

2021-03-28 21:14 UTC, PhilippHeuer commented on rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
> +    HystrixCommand<BadgeSets> getGlobalBadges(
Considering we're on java 8 i don't think we can make the helper methods private/not expose them - maybe we can deprecate them to discourage users from trying to use them?

2021-03-28 21:14 UTC, PhilippHeuer commented on rest-kraken/src/main/java/com/github/twitch4j/kraken/TwitchKraken.java
> +        URI baseUrl,
As above, maybe deprecate this method too.

2021-03-28 21:20 UTC, iProdigy commented
> I think the badges code might be a better fit for the tmi module as it's related to chat and isn't a kraken method. Maybe we could use tmi for any future api methods that are not kraken or helix.

Agreed; especially as twitch seems to be killing some of the current tmi endpoints so the module may become otherwise useless

2021-04-03 14:31 UTC, PhilippHeuer approved these changes

2021-04-03 17:21 UTC, merged